//
//  Cities.swift
//  imposter
//
//  Created by Tornike Despotashvili on 8/30/25.
//

import Foundation

let countriesCitiesData: [WordModel] = [
    // ქვეყნები
    WordModel(eng: "USA", geo: "ამერიკა", engHint: "Stars", geoHint: "ვარსკვლავები"),
    WordModel(eng: "Canada", geo: "კანადა", engHint: "Maple", geoHint: "ნეკერჩხალი"),
    WordModel(eng: "Mexico", geo: "მექსიკა", engHint: "Tacos", geoHint: "ტაკო"),
    WordModel(eng: "Brazil", geo: "ბრაზილია", engHint: "Samba", geoHint: "სამბა"),
    WordModel(eng: "Argentina", geo: "არგენტინა", engHint: "Tango", geoHint: "ტანგო"),
    WordModel(eng: "UK", geo: "დიდი ბრიტანეთი", engHint: "Queen", geoHint: "დედოფალი"),
    WordModel(eng: "France", geo: "საფრანგეთი", engHint: "Eiffel", geoHint: "ეიფელი"),
    WordModel(eng: "Germany", geo: "გერმანია", engHint: "Beer", geoHint: "ლუდი"),
    WordModel(eng: "Italy", geo: "იტალია", engHint: "Pasta", geoHint: "პასტა"),
    WordModel(eng: "Spain", geo: "ესპანეთი", engHint: "Bullfight", geoHint: "ხარები"),
    WordModel(eng: "Portugal", geo: "პორტუგალია", engHint: "Ocean", geoHint: "ოკეანე"),
    WordModel(eng: "Ireland", geo: "ირლანდია", engHint: "Green", geoHint: "მწვანე"),
    WordModel(eng: "Greece", geo: "საბერძნეთი", engHint: "Acropolis", geoHint: "აკროპოლისი"),
    WordModel(eng: "Egypt", geo: "ეგვიპტე", engHint: "Pyramids", geoHint: "სამარხი"),
    WordModel(eng: "South Africa", geo: "სამხრეთ აფრიკა", engHint: "Safari", geoHint: "საფარი"),
    WordModel(eng: "Nigeria", geo: "ნიგერია", engHint: "Nollywood", geoHint: "კინო"),
    WordModel(eng: "China", geo: "ჩინეთი", engHint: "Wall", geoHint: "კედელი"),
    WordModel(eng: "Japan", geo: "იაპონია", engHint: "Sushi", geoHint: "სუში"),
    WordModel(eng: "India", geo: "ინდოეთი", engHint: "Bollywood", geoHint: "ფილმები"),
    WordModel(eng: "Australia", geo: "ავსტრალია", engHint: "Kangaroo", geoHint: "კენგურუ"),
    WordModel(eng: "New Zealand", geo: "ახალი ზელანდია", engHint: "Kiwi", geoHint: "კივი"),
    WordModel(eng: "Russia", geo: "რუსეთი", engHint: "Kremlin", geoHint: "კრემლი"),
    WordModel(eng: "Turkey", geo: "თურქეთი", engHint: "Bosphorus", geoHint: "ბოსფორი"),
    WordModel(eng: "Sweden", geo: "შვედეთი", engHint: "IKEA", geoHint: "ავეჯი"),
    WordModel(eng: "Norway", geo: "ნორვეგია", engHint: "Fjords", geoHint: "ფიორდები"),
    WordModel(eng: "Denmark", geo: "დანია", engHint: "Lego", geoHint: "კუბიკები"),
    WordModel(eng: "Finland", geo: "ფინეთი", engHint: "Sauna", geoHint: "აბანო"),
    WordModel(eng: "Switzerland", geo: "შვეიცარია", engHint: "Alps", geoHint: "ალპები"),
    WordModel(eng: "Austria", geo: "ავსტრია", engHint: "Mozart", geoHint: "მუსიკა"),
    WordModel(eng: "Netherlands", geo: "ნიდერლანდები", engHint: "Tulips", geoHint: "ტიტები"),
    WordModel(eng: "Belgium", geo: "ბელგია", engHint: "Chocolate", geoHint: "შოკოლადი"),
    WordModel(eng: "Poland", geo: "პოლონეთი", engHint: "Pierogi", geoHint: "ღვეზელი"),
    WordModel(eng: "Czech Republic", geo: "ჩეხეთი", engHint: "Prague", geoHint: "პრაღა"),
    WordModel(eng: "Hungary", geo: "უნგრეთი", engHint: "Goulash", geoHint: "გულაში"),
    WordModel(eng: "Romania", geo: "რუმინეთი", engHint: "Dracula", geoHint: "დრაკულა"),
    WordModel(eng: "Bulgaria", geo: "ბულგარეთი", engHint: "Roses", geoHint: "ვარდები"),
    WordModel(eng: "Ukraine", geo: "უკრაინა", engHint: "Sunflower", geoHint: "მზესუმზირა"),
    WordModel(eng: "Georgia", geo: "საქართველო", engHint: "Wine", geoHint: "ღვინო"),
    WordModel(eng: "Azerbaijan", geo: "აზერბაიჯანი", engHint: "Baku", geoHint: "ბაქო"),
    WordModel(eng: "Armenia", geo: "სომხეთი", engHint: "Ararat", geoHint: "არარატი"),

    // ქალაქები
    WordModel(eng: "New York", geo: "ნიუ იორკი", engHint: "Statue", geoHint: "ქანდაკება"),
    WordModel(eng: "Los Angeles", geo: "ლოს ანჯელესი", engHint: "Hollywood", geoHint: "ჰოლივუდი"),
    WordModel(eng: "Chicago", geo: "ჩიკაგო", engHint: "Windy", geoHint: "ქარიანი"),
    WordModel(eng: "London", geo: "ლონდონი", engHint: "Tower", geoHint: "კოშკი"),
    WordModel(eng: "Paris", geo: "პარიზი", engHint: "Lights", geoHint: "ნათურები"),
    WordModel(eng: "Rome", geo: "რომი", engHint: "Colosseum", geoHint: "კოლიზეუმი"),
    WordModel(eng: "Berlin", geo: "ბერლინი", engHint: "Wall", geoHint: "კედელი"),
    WordModel(eng: "Madrid", geo: "მადრიდი", engHint: "Flamenco", geoHint: "ფლამენკო"),
    WordModel(eng: "Barcelona", geo: "ბარსელონა", engHint: "Gaudi", geoHint: "გაუდი"),
    WordModel(eng: "Amsterdam", geo: "ამსტერდამი", engHint: "Canals", geoHint: "არხები"),
    WordModel(eng: "Moscow", geo: "მოსკოვი", engHint: "Red", geoHint: "წითელი"),
    WordModel(eng: "Tokyo", geo: "ტოკიო", engHint: "Cherry", geoHint: "ალუბალი"),
    WordModel(eng: "Kyoto", geo: "კიოტო", engHint: "Temples", geoHint: "ტაძრები"),
    WordModel(eng: "Beijing", geo: "პეკინი", engHint: "Forbidden", geoHint: "აკრძალული"),
    WordModel(eng: "Shanghai", geo: "შანხაი", engHint: "Bund", geoHint: "ბუნდი"),
    WordModel(eng: "Sydney", geo: "სიდნეი", engHint: "Opera", geoHint: "ოპერა"),
    WordModel(eng: "Melbourne", geo: "მელბურნი", engHint: "Lanes", geoHint: "გამზირები"),
    WordModel(eng: "Dubai", geo: "დუბაი", engHint: "Burj", geoHint: "ბურჯი"),
    WordModel(eng: "Cairo", geo: "კაირო", engHint: "Nile", geoHint: "ნილოსი"),
    WordModel(eng: "Rio de Janeiro", geo: "რიო დე ჟანეირო", engHint: "Christ", geoHint: "ქრისტე"),
    WordModel(eng: "Buenos Aires", geo: "ბუენოს აირესი", engHint: "Cemetery", geoHint: "სასაფლაო"),
    WordModel(eng: "Cape Town", geo: "კეიპტაუნი", engHint: "Table", geoHint: "მაგიდა"),
    WordModel(eng: "Istanbul", geo: "სტამბოლი", engHint: "Hagia", geoHint: "აია"),
    WordModel(eng: "Lisbon", geo: "ლისაბონი", engHint: "Tram", geoHint: "ტრამვაი"),
    WordModel(eng: "Athens", geo: "ათენი", engHint: "Parthenon", geoHint: "პართენონი"),
    WordModel(eng: "Stockholm", geo: "სტოკჰოლმი", engHint: "Nobel", geoHint: "ნობელი"),
    WordModel(eng: "Oslo", geo: "ოსლო", engHint: "Fjord", geoHint: "ფიორდი"),
    WordModel(eng: "Copenhagen", geo: "კოპენჰაგენი", engHint: "Mermaid", geoHint: "ქალთევზა"),
    WordModel(eng: "Helsinki", geo: "ჰელსინკი", engHint: "Design", geoHint: "დიზაინი"),
    WordModel(eng: "Zurich", geo: "ციურიხი", engHint: "Banks", geoHint: "ბანკები"),
    WordModel(eng: "Geneva", geo: "ჟენევა", engHint: "Jet", geoHint: "შადრევანი"),
    WordModel(eng: "Vienna", geo: "ვენა", engHint: "Palace", geoHint: "სასახლე"),
    WordModel(eng: "Brussels", geo: "ბრიუსელი", engHint: "Manneken", geoHint: "შარდვა"),
    WordModel(eng: "Warsaw", geo: "ვარშავა", engHint: "Chopin", geoHint: "შოპენი"),
    WordModel(eng: "Prague", geo: "პრაღა", engHint: "Bridge", geoHint: "ხიდი"),
    WordModel(eng: "Budapest", geo: "ბუდაპეშტი", engHint: "Thermal", geoHint: "თერმული"),
    WordModel(eng: "Bucharest", geo: "ბუქარესტი", engHint: "Parliament", geoHint: "პარლამენტი"),
    WordModel(eng: "Sofia", geo: "სოფია", engHint: "Vitosha", geoHint: "ვიტოშა"),
    WordModel(eng: "Kyiv", geo: "კიევი", engHint: "Gold", geoHint: "ოქრო"),
    WordModel(eng: "Tbilisi", geo: "თბილისი", engHint: "Sulphur", geoHint: "გოგირდი"),
    WordModel(eng: "Baku", geo: "ბაქო", engHint: "Flame", geoHint: "ალი"),
    WordModel(eng: "Yerevan", geo: "ერევანი", engHint: "Cascade", geoHint: "კასკადი"),
    WordModel(eng: "Tehran", geo: "თეირანი", engHint: "Azadi", geoHint: "თავისუფლება"),
    WordModel(eng: "Seoul", geo: "სეული", engHint: "K-pop", geoHint: "კეიპოპი"),
    WordModel(eng: "Singapore", geo: "სინგაპური", engHint: "Merlion", geoHint: "მერლიონი"),
    WordModel(eng: "Bangkok", geo: "ბანგკოკი", engHint: "Temples", geoHint: "ტაძრები"),
    WordModel(eng: "Hanoi", geo: "ჰანოი", engHint: "Hoan", geoHint: "ტბა"),
    WordModel(eng: "Kuala Lumpur", geo: "კუალა ლუმპური", engHint: "Towers", geoHint: "კოშკები"),
    WordModel(eng: "Manila", geo: "მანილა", engHint: "Jeepney", geoHint: "ჯიპნი")
]
