//
//  EverydayObjects.swift
//  imposter
//
//  Created by Tornike Despotashvili on 8/23/25.
//

let everydayObjectsData: [WordModel] = [
  WordModel(eng: "Fork", geo: "ჩანგალი", engHint: "metal", geoHint: "ლითონი"),
  WordModel(eng: "Spoon", geo: "კოვზი", engHint: "soup", geoHint: "სუპი"),
  WordModel(eng: "Knife", geo: "დანა", engHint: "sharp", geoHint: "ბასრი"),
  WordModel(eng: "Plate", geo: "თეფში", engHint: "ceramic", geoHint: "კერამიკა"),
  WordModel(eng: "Cup", geo: "ფინჯანი", engHint: "handle", geoHint: "სახელური"),
  WordModel(eng: "Mug", geo: "ჭიქა", engHint: "coffee", geoHint: "ყავა"),
  WordModel(eng: "Glass", geo: "სასმისი", engHint: "transparent", geoHint: "გამჭვირვალე"),
  WordModel(eng: "Kettle", geo: "ჩაიდანი", engHint: "boil", geoHint: "ადუღება"),
  WordModel(eng: "Toaster", geo: "ტოსტერი", engHint: "bread", geoHint: "პური"),
  WordModel(eng: "Microwave", geo: "მიკროტალღური", engHint: "heat", geoHint: "გაცხელება"),
  WordModel(eng: "Refrigerator", geo: "მაცივარი", engHint: "cold", geoHint: "ცივი"),
  WordModel(eng: "Oven", geo: "ღუმელი", engHint: "bake", geoHint: "გამოცხობა"),
  WordModel(eng: "Sink", geo: "ნიჟარა", engHint: "water", geoHint: "წყალი"),
  WordModel(eng: "Sponge", geo: "ღრუბელი", engHint: "clean", geoHint: "სუფთა"),
  WordModel(eng: "Towel", geo: "პირსახოცი", engHint: "dry", geoHint: "გამშრალება"),
  WordModel(eng: "Trash can", geo: "ნაგვის ურნა", engHint: "waste", geoHint: "ნარჩენი"),
  WordModel(eng: "Blender", geo: "ბლენდერი", engHint: "smooth", geoHint: "ერთგვაროვანი"),
  WordModel(eng: "Cutting board", geo: "საჭრელი დაფა", engHint: "chop", geoHint: "დაჭრა"),
  WordModel(eng: "Pan", geo: "ტაფა", engHint: "fry", geoHint: "შეწვა"),
  WordModel(eng: "Pot", geo: "ქოთანი", engHint: "lid", geoHint: "თავსახური"),
  WordModel(eng: "Sofa", geo: "დივანი", engHint: "sit", geoHint: "ჯდომა"),
  WordModel(eng: "Chair", geo: "სკამი", engHint: "legs", geoHint: "ფეხები"),
  WordModel(eng: "Table", geo: "მაგიდა", engHint: "surface", geoHint: "ზედაპირი"),
  WordModel(eng: "Television", geo: "ტელევიზორი", engHint: "screen", geoHint: "ეკრანი"),
  WordModel(eng: "Remote", geo: "პულტი", engHint: "buttons", geoHint: "ღილაკები"),
  WordModel(eng: "Lamp", geo: "ლამპა", engHint: "light", geoHint: "სინათლე"),
  WordModel(eng: "Clock", geo: "საათი", engHint: "time", geoHint: "დრო"),
  WordModel(eng: "Door", geo: "კარი", engHint: "knob", geoHint: "სახელური"),
  WordModel(eng: "Window", geo: "ფანჯარა", engHint: "glass", geoHint: "მინა"),
  WordModel(eng: "Keys", geo: "გასაღები", engHint: "lock", geoHint: "საკეტი"),
  WordModel(eng: "Book", geo: "წიგნი", engHint: "pages", geoHint: "გვერდები"),
  WordModel(eng: "Shelf", geo: "თარო", engHint: "display", geoHint: "გამოფენა"),
  WordModel(eng: "Carpet", geo: "ხალიჩა", engHint: "floor", geoHint: "იატაკი"),
  WordModel(eng: "Vase", geo: "ლარნაკი", engHint: "flowers", geoHint: "ყვავილები"),
  WordModel(eng: "Curtains", geo: "ფარდები", engHint: "cover", geoHint: "დაფარვა"),
  WordModel(eng: "Mirror", geo: "სარკე", engHint: "reflection", geoHint: "ანარეკლი"),
  WordModel(eng: "Picture frame", geo: "ფოტოს ჩარჩო", engHint: "photo", geoHint: "ფოტო"),
  WordModel(eng: "Plant", geo: "მცენარე", engHint: "green", geoHint: "მწვანე"),
  WordModel(eng: "Stairs", geo: "კიბე", engHint: "steps", geoHint: "საფეხურები"),
  WordModel(eng: "Fireplace", geo: "ბუხარი", engHint: "warm", geoHint: "თბილი"),
  WordModel(eng: "Bed", geo: "საწოლი", engHint: "sleep", geoHint: "ძილი"),
  WordModel(eng: "Pillow", geo: "ბალიში", engHint: "head", geoHint: "თავი"),
  WordModel(eng: "Blanket", geo: "საბანი", engHint: "cozy", geoHint: "მყუდრო"),
  WordModel(eng: "Wardrobe", geo: "გარდერობი", engHint: "clothes", geoHint: "ტანსაცმელი"),
  WordModel(eng: "Hanger", geo: "საკიდი", engHint: "hang", geoHint: "დაკიდება"),
  WordModel(eng: "Dresser", geo: "კომოდი", engHint: "drawers", geoHint: "უჯრები"),
  WordModel(eng: "Alarm clock", geo: "მაღვიძარა", engHint: "wake", geoHint: "გაღვიძება"),
  WordModel(eng: "Nightstand", geo: "ტუმბო", engHint: "beside", geoHint: "გვერდით"),
  WordModel(eng: "Toothbrush", geo: "კბილის ჯაგრისი", engHint: "bristles", geoHint: "ჯაგარი"),
  WordModel(eng: "Toothpaste", geo: "კბილის პასტა", engHint: "mint", geoHint: "პიტნა"),
  WordModel(eng: "Soap", geo: "საპონი", engHint: "lather", geoHint: "აქაფება"),
  WordModel(eng: "Shampoo", geo: "შამპუნი", engHint: "hair", geoHint: "თმა"),
  WordModel(eng: "Shower", geo: "შხაპი", engHint: "spray", geoHint: "შესხურება"),
  WordModel(eng: "Toilet", geo: "ტუალეტი", engHint: "flush", geoHint: "ჩარეცხვა"),
  WordModel(eng: "Toilet paper", geo: "ტუალეტის ქაღალდი", engHint: "roll", geoHint: "რულონი"),
  WordModel(eng: "Faucet", geo: "ონკანი", engHint: "stream", geoHint: "ნაკადი"),
  WordModel(eng: "Comb", geo: "სავარცხელი", engHint: "teeth", geoHint: "კბილები"),
  WordModel(eng: "Hairbrush", geo: "თმის ჯაგრისი", engHint: "untangle", geoHint: "დავარცხნა"),
  WordModel(eng: "Razor", geo: "სამართებელი", engHint: "shave", geoHint: "გაპარსვა"),
  WordModel(eng: "Pen", geo: "კალამი", engHint: "ink", geoHint: "მელანი"),
  WordModel(eng: "Pencil", geo: "ფანქარი", engHint: "graphite", geoHint: "გრაფიტი"),
  WordModel(eng: "Paper", geo: "ქაღალდი", engHint: "sheet", geoHint: "ფურცელი"),
  WordModel(eng: "Notebook", geo: "რვეული", engHint: "lines", geoHint: "ხაზები"),
  WordModel(eng: "Scissors", geo: "მაკრატელი", engHint: "cut", geoHint: "ჭრა"),
  WordModel(eng: "Stapler", geo: "სტეპლერი", engHint: "attach", geoHint: "მიმაგრება"),
  WordModel(eng: "Computer", geo: "კომპიუტერი", engHint: "keyboard", geoHint: "კლავიატურა"),
  WordModel(eng: "Mouse", geo: "მაუსი", engHint: "click", geoHint: "დაწკაპუნება"),
  WordModel(eng: "Desk", geo: "სამუშაო მაგიდა", engHint: "work", geoHint: "მუშაობა"),
  WordModel(eng: "Bookshelf", geo: "წიგნის თარო", engHint: "spine", geoHint: "ყუა"),
  WordModel(eng: "Eraser", geo: "საშლელი", engHint: "mistake", geoHint: "შეცდომა"),
  WordModel(eng: "Glue", geo: "წებო", engHint: "stick", geoHint: "მიწებება"),
  WordModel(eng: "Tape", geo: "სკოჩი", engHint: "adhesive", geoHint: "წებოვანი"),
  WordModel(eng: "Phone", geo: "ტელეფონი", engHint: "call", geoHint: "ზარი"),
  WordModel(eng: "Wallet", geo: "საფულე", engHint: "money", geoHint: "ფული"),
  WordModel(eng: "Backpack", geo: "ზურგჩანთა", engHint: "carry", geoHint: "ტარება"),
  WordModel(eng: "Handbag", geo: "ხელჩანთა", engHint: "strap", geoHint: "თასმა"),
  WordModel(eng: "Watch", geo: "მაჯის საათი", engHint: "wrist", geoHint: "მაჯა"),
  WordModel(eng: "Glasses", geo: "სათვალე", engHint: "see", geoHint: "ხედვა"),
  WordModel(eng: "Umbrella", geo: "ქოლგა", engHint: "rain", geoHint: "წვიმა"),
  WordModel(eng: "Hat", geo: "ქუდი", engHint: "head", geoHint: "თავი"),
  WordModel(eng: "Shoes", geo: "ფეხსაცმელი", engHint: "feet", geoHint: "ტერფები"),
  WordModel(eng: "Socks", geo: "წინდები", engHint: "pair", geoHint: "წყვილი"),
  WordModel(eng: "Jacket", geo: "ქურთუკი", engHint: "wear", geoHint: "ჩაცმა"),
  WordModel(eng: "Headphones", geo: "ყურსასმენები", engHint: "listen", geoHint: "მოსმენა"),
  WordModel(eng: "Water bottle", geo: "წყლის ბოთლი", engHint: "drink", geoHint: "სმა"),
  WordModel(eng: "Light bulb", geo: "ნათურა", engHint: "filament", geoHint: "ძაფი"),
  WordModel(eng: "Battery", geo: "ელემენტი", engHint: "power", geoHint: "ენერგია"),
  WordModel(eng: "Candle", geo: "სანთელი", engHint: "wax", geoHint: "ცვილი"),
  WordModel(eng: "Broom", geo: "ცოცხი", engHint: "sweep", geoHint: "გახვეტა"),
  WordModel(eng: "Dustpan", geo: "აქანდაზი", engHint: "collect", geoHint: "შეგროვება"),
  WordModel(eng: "Iron", geo: "უთო", engHint: "press", geoHint: "დაუთოება"),
  WordModel(eng: "Ironing board", geo: "საუთოო მაგიდა", engHint: "flat", geoHint: "ბრტყელი"),
  WordModel(eng: "Laundry basket", geo: "სარეცხის კალათა", engHint: "dirty", geoHint: "ჭუჭყიანი"),
  WordModel(eng: "Washing machine", geo: "სარეცხი მანქანა", engHint: "spin", geoHint: "ბრუნვა"),
  WordModel(eng: "Dryer", geo: "საშრობი", engHint: "heat", geoHint: "სითბო"),
  WordModel(eng: "Hammer", geo: "ჩაქუჩი", engHint: "nail", geoHint: "ლურსმანი"),
  WordModel(eng: "Screwdriver", geo: "სახრახნისი", engHint: "turn", geoHint: "დატრიალება"),
  WordModel(eng: "Ladder", geo: "გადასატანი კიბე", engHint: "climb", geoHint: "ასვლა"),
  WordModel(eng: "Bucket", geo: "ვედრო", engHint: "handle", geoHint: "სახელური"),
  WordModel(eng: "Switch", geo: "ჩამრთველი", engHint: "on/off", geoHint: "ჩართვა/გამორთვა")
]


