//
//  anomals.swift
//  imposter
//
//  Created by Tornike Despotashvili on 8/23/25.
//

import Foundation

let floraAndFaunaData: [WordModel] = [
  WordModel(eng: "Lion", geo: "ლომი", engHint: "mane", geoHint: "ფაფარი"),
  WordModel(eng: "Tiger", geo: "ვეფხვი", engHint: "stripes", geoHint: "ზოლები"),
  WordModel(eng: "Elephant", geo: "სპილო", engHint: "trunk", geoHint: "ხორთუმი"),
  WordModel(eng: "Giraffe", geo: "ჟირაფი", engHint: "neck", geoHint: "კისერი"),
  WordModel(eng: "Zebra", geo: "ზებრა", engHint: "black and white", geoHint: "შავ-თეთრი"),
  WordModel(eng: "Bear", geo: "დათვი", engHint: "hibernation", geoHint: "ზამთრის ძილი"),
  WordModel(eng: "Wolf", geo: "მგელი", engHint: "pack", geoHint: "ხროვა"),
  WordModel(eng: "Fox", geo: "მელია", engHint: "cunning", geoHint: "ცბიერი"),
  WordModel(eng: "Dog", geo: "ძაღლი", engHint: "bark", geoHint: "ყეფა"),
  WordModel(eng: "Cat", geo: "კატა", engHint: "purr", geoHint: "კრუტუნი"),
  WordModel(eng: "Horse", geo: "ცხენი", engHint: "hoof", geoHint: "ჩლიქი"),
  WordModel(eng: "Cow", geo: "ძროხა", engHint: "moo", geoHint: "ბღავილი"),
  WordModel(eng: "Sheep", geo: "ცხვარი", engHint: "wool", geoHint: "მატყლი"),
  WordModel(eng: "Pig", geo: "ღორი", engHint: "snout", geoHint: "დინგი"),
  WordModel(eng: "Monkey", geo: "მაიმუნი", engHint: "swing", geoHint: "ქანაობა"),
  WordModel(eng: "Kangaroo", geo: "კენგურუ", engHint: "pouch", geoHint: "ჩანთა"),
  WordModel(eng: "Bat", geo: "ღამურა", engHint: "echo", geoHint: "ექო"),
  WordModel(eng: "Eagle", geo: "არწივი", engHint: "soar", geoHint: "ნავარდი"),
  WordModel(eng: "Owl", geo: "ბუ", engHint: "nocturnal", geoHint: "ღამის"),
  WordModel(eng: "Penguin", geo: "პინგვინი", engHint: "ice", geoHint: "ყინული"),
  WordModel(eng: "Parrot", geo: "თუთიყუში", engHint: "mimic", geoHint: "იმიტაცია"),
  WordModel(eng: "Flamingo", geo: "ფლამინგო", engHint: "pink", geoHint: "ვარდისფერი"),
  WordModel(eng: "Swan", geo: "გედი", engHint: "graceful", geoHint: "გრაციოზული"),
  WordModel(eng: "Snake", geo: "გველი", engHint: "shed", geoHint: "კანის ცვლა"),
  WordModel(eng: "Lizard", geo: "ხვლიკი", engHint: "tail", geoHint: "კუდი"),
  WordModel(eng: "Turtle", geo: "კუ", engHint: "shell", geoHint: "ბაკანი"),
  WordModel(eng: "Crocodile", geo: "ნიანგი", engHint: "jaw", geoHint: "ყბა"),
  WordModel(eng: "Frog", geo: "ბაყაყი", engHint: "jump", geoHint: "ხტომა"),
  WordModel(eng: "Fish", geo: "თევზი", engHint: "scales", geoHint: "ქერცლი"),
  WordModel(eng: "Shark", geo: "ზვიგენი", engHint: "fin", geoHint: "ფარფლი"),
  WordModel(eng: "Whale", geo: "ვეშაპი", engHint: "blowhole", geoHint: "შადრევანი"),
  WordModel(eng: "Dolphin", geo: "დელფინი", engHint: "intelligent", geoHint: "ჭკვიანი"),
  WordModel(eng: "Octopus", geo: "რვაფეხა", engHint: "ink", geoHint: "მელანი"),
  WordModel(eng: "Crab", geo: "კიბორჩხალა", engHint: "claw", geoHint: "მარწუხი"),
  WordModel(eng: "Spider", geo: "ობობა", engHint: "web", geoHint: "ქსელი"),
  WordModel(eng: "Bee", geo: "ფუტკარი", engHint: "honey", geoHint: "თაფლი"),
  WordModel(eng: "Ant", geo: "ჭიანჭველა", engHint: "colony", geoHint: "კოლონია"),
  WordModel(eng: "Butterfly", geo: "პეპელა", engHint: "wings", geoHint: "ფრთები"),
  WordModel(eng: "Mosquito", geo: "კოღო", engHint: "bite", geoHint: "კბენა"),
  WordModel(eng: "Snail", geo: "ლოკოკინა", engHint: "slime", geoHint: "ლორწო"),
  WordModel(eng: "Rabbit", geo: "კურდღელი", engHint: "ears", geoHint: "ყურები"),
  WordModel(eng: "Deer", geo: "ირემი", engHint: "antlers", geoHint: "რქები"),
  WordModel(eng: "Camel", geo: "აქლემი", engHint: "hump", geoHint: "კუზი"),
  WordModel(eng: "Squirrel", geo: "ციყვი", engHint: "nuts", geoHint: "თხილი"),
  WordModel(eng: "Mouse", geo: "თაგვი", engHint: "squeak", geoHint: "წრიპინი"),
  WordModel(eng: "Hedgehog", geo: "ზღარბი", engHint: "spikes", geoHint: "ეკლები"),
  WordModel(eng: "Peacock", geo: "ფარშევანგი", engHint: "feathers", geoHint: "ბუმბული"),
  WordModel(eng: "Jellyfish", geo: "მედუზა", engHint: "sting", geoHint: "დაგესვლა"),
  WordModel(eng: "Starfish", geo: "ზღვის ვარსკვლავი", engHint: "arms", geoHint: "სხივები"),
  WordModel(eng: "Goat", geo: "თხა", engHint: "beard", geoHint: "წვერი"),
  WordModel(eng: "Rose", geo: "ვარდი", engHint: "thorn", geoHint: "ეკალი"),
  WordModel(eng: "Sunflower", geo: "მზესუმზირა", engHint: "sun", geoHint: "მზე"),
  WordModel(eng: "Tulip", geo: "ტიტა", engHint: "bulb", geoHint: "ბოლქვი"),
  WordModel(eng: "Daisy", geo: "გვირილა", engHint: "petals", geoHint: "ფურცლები"),
  WordModel(eng: "Orchid", geo: "ორქიდეა", engHint: "exotic", geoHint: "ეგზოტიკური"),
  WordModel(eng: "Dandelion", geo: "ბაბუაწვერა", engHint: "blow", geoHint: "შებერვა"),
  WordModel(eng: "Poppy", geo: "ყაყაჩო", engHint: "red", geoHint: "წითელი"),
  WordModel(eng: "Violet", geo: "ია", engHint: "purple", geoHint: "იისფერი"),
  WordModel(eng: "Oak", geo: "მუხა", engHint: "acorn", geoHint: "რკო"),
  WordModel(eng: "Pine", geo: "ფიჭვი", engHint: "needle", geoHint: "წიწვი"),
  WordModel(eng: "Maple", geo: "ნეკერჩხალი", engHint: "syrup", geoHint: "სიროფი"),
  WordModel(eng: "Birch", geo: "არყის ხე", engHint: "bark", geoHint: "ქერქი"),
  WordModel(eng: "Willow", geo: "ტირიფი", engHint: "weep", geoHint: "ტირილი"),
  WordModel(eng: "Palm Tree", geo: "პალმა", engHint: "coast", geoHint: "სანაპირო"),
  WordModel(eng: "Baobab", geo: "ბაობაბი", engHint: "thick", geoHint: "სქელი"),
  WordModel(eng: "Sequoia", geo: "სექვოია", engHint: "giant", geoHint: "გიგანტი"),
  WordModel(eng: "Fern", geo: "გვიმრა", engHint: "spore", geoHint: "სპორა"),
  WordModel(eng: "Moss", geo: "ხავსი", engHint: "damp", geoHint: "ნესტიანი"),
  WordModel(eng: "Ivy", geo: "სურო", engHint: "climb", geoHint: "ცოცვა"),
  WordModel(eng: "Cactus", geo: "კაქტუსი", engHint: "desert", geoHint: "უდაბნო"),
  WordModel(eng: "Aloe Vera", geo: "ალოე", engHint: "gel", geoHint: "გელი"),
  WordModel(eng: "Bamboo", geo: "ბამბუკი", engHint: "panda", geoHint: "პანდა"),
  WordModel(eng: "Wheat", geo: "ხორბალი", engHint: "field", geoHint: "ყანა"),
  WordModel(eng: "Sugarcane", geo: "შაქრის ლერწამი", engHint: "sweet", geoHint: "ტკბილი"),
  WordModel(eng: "Cotton", geo: "ბამბა", engHint: "fiber", geoHint: "ბოჭკო"),
  WordModel(eng: "Mushroom", geo: "სოკო", engHint: "cap", geoHint: "ქუდი"),
  WordModel(eng: "Seaweed", geo: "წყალმცენარე", engHint: "ocean", geoHint: "ოკეანე"),
  WordModel(eng: "Venus Flytrap", geo: "ბუზიჭერია", engHint: "trap", geoHint: "ხაფანგი"),
  WordModel(eng: "Clover", geo: "სამყურა", engHint: "luck", geoHint: "იღბალი"),
  WordModel(eng: "Lavender", geo: "ლავანდა", engHint: "scent", geoHint: "სურნელი"),
  WordModel(eng: "Mint", geo: "პიტნა", engHint: "cool", geoHint: "გრილი"),
  WordModel(eng: "Rosemary", geo: "როზმარინი", engHint: "herb", geoHint: "მწვანილი"),
  WordModel(eng: "Basil", geo: "რეჰანი", engHint: "pesto", geoHint: "პესტო"),
  WordModel(eng: "Cherry Blossom", geo: "საკურა", engHint: "Japan", geoHint: "იაპონია"),
  WordModel(eng: "Lotus", geo: "ლოტოსი", engHint: "pond", geoHint: "ტბორი"),
  WordModel(eng: "Ginseng", geo: "ჟენშენი", engHint: "root", geoHint: "ფესვი"),
  WordModel(eng: "Papyrus", geo: "პაპირუსი", engHint: "paper", geoHint: "ქაღალდი"),
  WordModel(eng: "Edelweiss", geo: "ედელვაისი", engHint: "mountain", geoHint: "მთა"),
  WordModel(eng: "Fir", geo: "სოჭი", engHint: "Christmas", geoHint: "შობა"),
  WordModel(eng: "Spruce", geo: "ნაძვი", engHint: "cone", geoHint: "გირჩა"),
  WordModel(eng: "Cypress", geo: "კვიპაროსი", engHint: "tall", geoHint: "მაღალი"),
  WordModel(eng: "Nettle", geo: "ჭინჭარი", engHint: "sting", geoHint: "დასუსხვა"),
  WordModel(eng: "Bonsai", geo: "ბონსაი", engHint: "miniature", geoHint: "მინიატურა"),
  WordModel(eng: "Vine", geo: "ვაზი", engHint: "grape", geoHint: "ყურძენი"),
  WordModel(eng: "Algae", geo: "წყალმცენარეები", engHint: "green water", geoHint: "მწვანე წყალი")
]
