//
//  Food.swift
//  imposter
//
//  Created by Tornike Despotashvili on 8/30/25.
//

import Foundation

let foodAndDrinksData: [WordModel] = [
  WordModel(eng: "Apple", geo: "ვაშლი", engHint: "fruit", geoHint: "ხილი"),
  WordModel(eng: "Banana", geo: "ბანანი", engHint: "yellow", geoHint: "ყვითელი"),
  WordModel(eng: "Orange", geo: "ფორთოხალი", engHint: "citrus", geoHint: "ციტრუსი"),
  WordModel(eng: "Bread", geo: "პური", engHint: "baked", geoHint: "გამომცხვარი"),
  WordModel(eng: "Cheese", geo: "ყველი", engHint: "dairy", geoHint: "რძის"),
  WordModel(eng: "Milk", geo: "რძე", engHint: "white", geoHint: "თეთრი"),
  WordModel(eng: "Water", geo: "წყალი", engHint: "liquid", geoHint: "სითხე"),
  WordModel(eng: "Coffee", geo: "ყავა", engHint: "caffeine", geoHint: "კოფეინი"),
  WordModel(eng: "Tea", geo: "ჩაი", engHint: "leaves", geoHint: "ფოთლები"),
  WordModel(eng: "Juice", geo: "წვენი", engHint: "drink", geoHint: "სასმელი"),
  WordModel(eng: "Egg", geo: "კვერცხი", engHint: "protein", geoHint: "ცილა"),
  WordModel(eng: "Meat", geo: "ხორცი", engHint: "protein", geoHint: "ცილა"),
  WordModel(eng: "Chicken", geo: "ქათამი", engHint: "poultry", geoHint: "ფრინველი"),
  WordModel(eng: "Fish", geo: "თევზი", engHint: "seafood", geoHint: "ზღვის"),
  WordModel(eng: "Rice", geo: "ბრინჯი", engHint: "grain", geoHint: "მარცვლეული"),
  WordModel(eng: "Pasta", geo: "მაკარონი", engHint: "noodles", geoHint: "ცომი"),
  WordModel(eng: "Potato", geo: "კარტოფილი", engHint: "vegetable", geoHint: "ბოსტნეული"),
  WordModel(eng: "Tomato", geo: "პომიდორი", engHint: "red", geoHint: "წითელი"),
  WordModel(eng: "Onion", geo: "ხახვი", engHint: "bulb", geoHint: "ბოლქვი"),
  WordModel(eng: "Garlic", geo: "ნიორი", engHint: "pungent", geoHint: "მკვეთრი"),
  WordModel(eng: "Carrot", geo: "სტაფილო", engHint: "orange", geoHint: "ნარინჯისფერი"),
  WordModel(eng: "Cucumber", geo: "კიტრი", engHint: "green", geoHint: "მწვანე"),
  WordModel(eng: "Salad", geo: "სალათი", engHint: "greens", geoHint: "მწვანილი"),
  WordModel(eng: "Soup", geo: "სუპი", engHint: "broth", geoHint: "ბულიონი"),
  WordModel(eng: "Pizza", geo: "პიცა", engHint: "italian", geoHint: "იტალიური"),
  WordModel(eng: "Burger", geo: "ბურგერი", engHint: "sandwich", geoHint: "სენდვიჩი"),
  WordModel(eng: "Fries", geo: "კარტოფილი ფრი", engHint: "fried", geoHint: "შემწვარი"),
  WordModel(eng: "Hotdog", geo: "ჰოთდოგი", engHint: "sausage", geoHint: "ძეხვი"),
  WordModel(eng: "Sandwich", geo: "სენდვიჩი", engHint: "layers", geoHint: "ფენები"),
  WordModel(eng: "Cake", geo: "ტორტი", engHint: "dessert", geoHint: "დესერტი"),
  WordModel(eng: "Cookie", geo: "ორცხობილა", engHint: "sweet", geoHint: "ტკბილი"),
  WordModel(eng: "Ice Cream", geo: "ნაყინი", engHint: "cold", geoHint: "ცივი"),
  WordModel(eng: "Chocolate", geo: "შოკოლადი", engHint: "cocoa", geoHint: "კაკაო"),
  WordModel(eng: "Candy", geo: "კანფეტი", engHint: "sugar", geoHint: "შაქარი"),
  WordModel(eng: "Honey", geo: "თაფლი", engHint: "sweetener", geoHint: "დამატკბობელი"),
  WordModel(eng: "Sugar", geo: "შაქარი", engHint: "crystals", geoHint: "კრისტალები"),
  WordModel(eng: "Salt", geo: "მარილი", engHint: "seasoning", geoHint: "სანელებელი"),
  WordModel(eng: "Pepper", geo: "წიწაკა", engHint: "spice", geoHint: "სანელებელი"),
  WordModel(eng: "Oil", geo: "ზეთი", engHint: "cooking", geoHint: "კულინარია"),
  WordModel(eng: "Vinegar", geo: "ძმარი", engHint: "acid", geoHint: "მჟავა"),
  WordModel(eng: "Butter", geo: "კარაქი", engHint: "fat", geoHint: "ცხიმი"),
  WordModel(eng: "Yogurt", geo: "იოგურტი", engHint: "fermented", geoHint: "ფერმენტირებული"),
  WordModel(eng: "Cream", geo: "ნაღები", engHint: "dairy", geoHint: "რძის"),
  WordModel(eng: "Jam", geo: "ჯემი", engHint: "spread", geoHint: "სპრედი"),
  WordModel(eng: "Syrup", geo: "სიროფი", engHint: "thick", geoHint: "სქელი"),
  WordModel(eng: "Nuts", geo: "თხილი", engHint: "snack", geoHint: "საუზმე"),
  WordModel(eng: "Seeds", geo: "თესლი", engHint: "small", geoHint: "პატარა"),
  WordModel(eng: "Beans", geo: "ლობიო", engHint: "legume", geoHint: "პარკოსანი"),
  WordModel(eng: "Lentils", geo: "ოსპი", engHint: "pulses", geoHint: "პარკოსნები"),
  WordModel(eng: "Oats", geo: "შვრია", engHint: "cereal", geoHint: "მარცვლეული"),
  WordModel(eng: "Cereal", geo: "მარცვლეული", engHint: "breakfast", geoHint: "საუზმე"),
  WordModel(eng: "Pancake", geo: "ბლინი", engHint: "flat", geoHint: "ბრტყელი"),
  WordModel(eng: "Waffle", geo: "ვაფლი", engHint: "grid", geoHint: "ბადე"),
  WordModel(eng: "Muffin", geo: "მაფინი", engHint: "cupcake", geoHint: "კექსი"),
  WordModel(eng: "Donut", geo: "დონატი", engHint: "ring", geoHint: "ბეჭედი"),
  WordModel(eng: "Croissant", geo: "კრუასანი", engHint: "pastry", geoHint: "ფუნთუშა"),
  WordModel(eng: "Bagel", geo: "ბაგელი", engHint: "doughnut", geoHint: "ფუნთუშა"),
  WordModel(eng: "Pretzel", geo: "პრეტცელი", engHint: "knotted", geoHint: "კვანძი"),
  WordModel(eng: "Cracker", geo: "კრეკერი", engHint: "crisp", geoHint: "ხრაშუნა"),
  WordModel(eng: "Chip", geo: "ჩიპი", engHint: "crispy", geoHint: "ხრაშუნა"),
  WordModel(eng: "Popcorn", geo: "პოპკორნი", engHint: "kernels", geoHint: "მარცვლები"),
  WordModel(eng: "Gum", geo: "საღეჭი რეზინი", engHint: "chewy", geoHint: "საღეჭი"),
  WordModel(eng: "Soda", geo: "გამაგრილებელი სასმელი", engHint: "bubbly", geoHint: "ბუშტებიანი"),
  WordModel(eng: "Beer", geo: "ლუდი", engHint: "alcoholic", geoHint: "ალკოჰოლური"),
  WordModel(eng: "Wine", geo: "ღვინო", engHint: "grapes", geoHint: "ყურძენი"),
  WordModel(eng: "Vodka", geo: "არაყი", engHint: "spirit", geoHint: "სპირტი"),
  WordModel(eng: "Whiskey", geo: "ვისკი", engHint: "aged", geoHint: "დაძველებული"),
  WordModel(eng: "Rum", geo: "რომი", engHint: "sugarcane", geoHint: "შაქრის ლერწამი"),
  WordModel(eng: "Gin", geo: "ჯინი", engHint: "botanical", geoHint: "ბოტანიკური"),
  WordModel(eng: "Tequila", geo: "ტეკილა", engHint: "agave", geoHint: "აგავა"),
  WordModel(eng: "Cocktail", geo: "კოქტეილი", engHint: "mixed", geoHint: "შერეული"),
  WordModel(eng: "Smoothie", geo: "სმუზი", engHint: "blended", geoHint: "შერეული"),
  WordModel(eng: "Shake", geo: "შეიკი", engHint: "thick", geoHint: "სქელი"),
  WordModel(eng: "Lemonade", geo: "ლიმონათი", engHint: "sour", geoHint: "მჟავე"),
  WordModel(eng: "Lime", geo: "ლაიმი", engHint: "green", geoHint: "მწვანე"),
  WordModel(eng: "Ginger", geo: "ჯანჯაფილი", engHint: "root", geoHint: "ფესვი"),
  WordModel(eng: "Mint", geo: "პიტნა", engHint: "herb", geoHint: "ბალახი"),
  WordModel(eng: "Basil", geo: "რეჰანი", engHint: "fragrant", geoHint: "სურნელოვანი"),
  WordModel(eng: "Cilantro", geo: "ქინძი", engHint: "herb", geoHint: "ბალახი"),
  WordModel(eng: "Parsley", geo: "ოხრახუში", engHint: "green", geoHint: "მწვანე"),
  WordModel(eng: "Rosemary", geo: "როზმარინი", engHint: "aromatic", geoHint: "არომატული"),
  WordModel(eng: "Thyme", geo: "თიამი", engHint: "spice", geoHint: "სანელებელი"),
  WordModel(eng: "Oregano", geo: "ორეგანო", engHint: "pizza", geoHint: "პიცა"),
  WordModel(eng: "Bay Leaf", geo: "დაფნის ფოთოლი", engHint: "fragrant", geoHint: "სურნელოვანი"),
  WordModel(eng: "Cinnamon", geo: "დარიჩინი", engHint: "bark", geoHint: "ქერქი"),
  WordModel(eng: "Nutmeg", geo: "მუსკატის კაკალი", engHint: "spice", geoHint: "სანელებელი"),
  WordModel(eng: "Clove", geo: "მიხაკი", engHint: "flowerbud", geoHint: "კვირტი"),
  WordModel(eng: "Vanilla", geo: "ვანილი", engHint: "pod", geoHint: "ღერო"),
  WordModel(eng: "Saffron", geo: "ზაფრანა", engHint: "expensive", geoHint: "ძვირი"),
  WordModel(eng: "Curry", geo: "კარი", engHint: "blend", geoHint: "ნარევი"),
  WordModel(eng: "Mustard", geo: "მდოგვი", engHint: "condiment", geoHint: "სანელებელი"),
  WordModel(eng: "Ketchup", geo: "კეტჩუპი", engHint: "tomato", geoHint: "პომიდორი"),
  WordModel(eng: "Mayonnaise", geo: "მაიონეზი", engHint: "creamy", geoHint: "კრემისებური"),
  WordModel(eng: "Soy Sauce", geo: "სოიოს სოუსი", engHint: "salty", geoHint: "მარილიანი"),
  WordModel(eng: "Worcestershire", geo: "ვუსტერშირის სოუსი", engHint: "savory", geoHint: "მარილიანი"),
  WordModel(eng: "Tabasco", geo: "ტაბასკო", engHint: "hot", geoHint: "ცხელი"),
  WordModel(eng: "Hummus", geo: "ჰუმუსი", engHint: "chickpea", geoHint: "წიწიბურა"),
  WordModel(eng: "Guacamole", geo: "გუაკამოლე", engHint: "avocado", geoHint: "ავოკადო"),
  WordModel(eng: "Salsa", geo: "სალსა", engHint: "dip", geoHint: "სოუსი"),
  WordModel(eng: "Jelly", geo: "ჟელე", engHint: "fruit", geoHint: "ხილი")
]
