//
//  HarryPotter.swift
//  imposter
//
//  Created by Tornike Despotashvili on 8/30/25.
//

import Foundation

let harryPotterWordsData: [WordModel] = [
    WordModel(eng: "Wand", geo: "ჯოხი", engHint: "magic", geoHint: "მაგია"),
    WordModel(eng: "Potion", geo: "წამალი", engHint: "brew", geoHint: "ხარშვა"),
    WordModel(eng: "Spell", geo: "შელოცვა", engHint: "incantation", geoHint: "შელოცვა"),
    WordModel(eng: "Quidditch", geo: "ქვიდიჩი", engHint: "sport", geoHint: "სპორტი"),
    WordModel(eng: "Hogwarts", geo: "ჰოგვარტსი", engHint: "school", geoHint: "სკოლა"),
    WordModel(eng: "Muggle", geo: "მაგლი", engHint: "non-magic", geoHint: "არამაგიური"),
    WordModel(eng: "Nimbus", geo: "ნიმბუსი", engHint: "broom", geoHint: "ცოცხი"),
    WordModel(eng: "Galleon", geo: "გალიონი", engHint: "coin", geoHint: "მონეტა"),
    WordModel(eng: "House", geo: "ფაკულტეტი", engHint: "group", geoHint: "ჯგუფი"),
    WordModel(eng: "Snitch", geo: "სნიჩი", engHint: "golden", geoHint: "ოქროსფერი"),
    WordModel(eng: "Horcrux", geo: "ჰორკრუქსი", engHint: "fragment", geoHint: "ფრაგმენტი"),
    WordModel(eng: "Patronus", geo: "პატრონუსი", engHint: "charm", geoHint: "შარმი"),
    WordModel(eng: "Azkaban", geo: "აზკაბანი", engHint: "prison", geoHint: "ციხე"),
    WordModel(eng: "Owl", geo: "ბუ", engHint: "messenger", geoHint: "მესენჯერი"),
    WordModel(eng: "Cauldron", geo: "ქვაბი", engHint: "metal", geoHint: "ლითონი"),
    WordModel(eng: "Diagon Alley", geo: "დიაგონ-ხეივანი", engHint: "shopping", geoHint: "შოპინგი"),
    WordModel(eng: "Unicorn", geo: "უნიკორნი", engHint: "mythical", geoHint: "მითიური"),
    WordModel(eng: "Phoenix", geo: "ფენიქსი", engHint: "bird", geoHint: "ჩიტი"),
    WordModel(eng: "Dragon", geo: "დრაკონი", engHint: "reptile", geoHint: "ქვეწარმავალი"),
    WordModel(eng: "Elder Wand", geo: "ბაბუაწვერას ჯოხი", engHint: "powerful", geoHint: "ძლიერი"),
    WordModel(eng: "Cloak", geo: "მოსასხამი", engHint: "invisibility", geoHint: "უხილავობა"),
    WordModel(eng: "Marauder", geo: "მარაუდერი", engHint: "map", geoHint: "რუკა"),
    WordModel(eng: "Dementor", geo: "დემენტორი", engHint: "soul", geoHint: "სული"),
    WordModel(eng: "Goblin", geo: "გობლინი", engHint: "banker", geoHint: "ბანკირი"),
    WordModel(eng: "Centaur", geo: "კენტავრი", engHint: "forest", geoHint: "ტყე"),
    WordModel(eng: "Bludger", geo: "ბლაგერი", engHint: "ball", geoHint: "ბურთი"),
    WordModel(eng: "Seeker", geo: "მძებნელი", engHint: "player", geoHint: "მოთამაშე"),
    WordModel(eng: "Grindelwald", geo: "გრინდელვალდი", engHint: "dark", geoHint: "ბნელი"),
    WordModel(eng: "Prophecy", geo: "წინასწარმეტყველება", engHint: "future", geoHint: "მომავალი"),
    WordModel(eng: "Animagus", geo: "ანიმაგუსი", engHint: "shape-shift", geoHint: "ფორმის შეცვლა"),
    WordModel(eng: "Polyjuice", geo: "პოლიწვენი", engHint: "transformation", geoHint: "ტრანსფორმაცია"),
    WordModel(eng: "Time-Turner", geo: "დროის-მობრუნებელი", engHint: "chronology", geoHint: "ქრონოლოგია"),
    WordModel(eng: "Parseltongue", geo: "პარსელტანგი", engHint: "snake", geoHint: "გველი"),
    WordModel(eng: "Banshee", geo: "ბანში", engHint: "scream", geoHint: "კივილი"),
    WordModel(eng: "Werewolf", geo: "მაქცია", engHint: "moon", geoHint: "მთვარე"),
    WordModel(eng: "Gringotts", geo: "გრინგოტსი", engHint: "vault", geoHint: "სარდაფი"),
    WordModel(eng: "Fawkes", geo: "ფოუქსი", engHint: "Dumbledore", geoHint: "დამბლდორი"),
    WordModel(eng: "Basilisk", geo: "ბაზილისკი", engHint: "glance", geoHint: "გამოხედვა"),
    WordModel(eng: "Thestral", geo: "თესტრალი", engHint: "invisible", geoHint: "უხილავი"),
    WordModel(eng: "Portkey", geo: "პორტკი", engHint: "travel", geoHint: "მოგზაურობა"),
    WordModel(eng: "Floo Powder", geo: "ფლუს ფხვნილი", engHint: "fireplace", geoHint: "ბუხარი"),
    WordModel(eng: "Pensieve", geo: "პენსივი", engHint: "memory", geoHint: "მეხსიერება"),
    WordModel(eng: "Blast-Ended Skrewt", geo: "ბლასტ-ენდედ სკრუტა", engHint: "dangerous", geoHint: "საშიში"),
    WordModel(eng: "Acromantula", geo: "აკრომანტულა", engHint: "spider", geoHint: "ობობა"),
    WordModel(eng: "Hippogriff", geo: "ჰიპოგრიფი", engHint: "flight", geoHint: "ფრენა"),
    WordModel(eng: "Death Eater", geo: "სიკვდილის მჭამელი", engHint: "follower", geoHint: "მიმდევარი"),
    WordModel(eng: "Ministry", geo: "სამინისტრო", engHint: "government", geoHint: "მთავრობა"),
    WordModel(eng: "Auror", geo: "ავრორა", engHint: "defender", geoHint: "დამცველი"),
    WordModel(eng: "Squib", geo: "სქვიბი", engHint: "no-magic", geoHint: "უმაგიო"),
    WordModel(eng: "Felix Felicis", geo: "ფელიქს ფელიცისი", engHint: "luck", geoHint: "იღბალი"),
    WordModel(eng: "Veritaserum", geo: "ვერიტასერუმი", engHint: "truth", geoHint: "სიმართლე"),
    WordModel(eng: "Invisibility Cloak", geo: "უხილავობის მოსასხამი", engHint: "concealment", geoHint: "დაფარვა"),
    WordModel(eng: "Mirror of Erised", geo: "ერისიდას სარკე", engHint: "desire", geoHint: "სურვილი"),
    WordModel(eng: "Sorting Hat", geo: "განაწილების ქუდი", engHint: "decision", geoHint: "გადაწყვეტილება"),
    WordModel(eng: "Devilish Snare", geo: "ეშმაკის ხაფანგი", engHint: "plant", geoHint: "მცენარე"),
    WordModel(eng: "Goblet of Fire", geo: "ცეცხლოვანი ფიალა", engHint: "tournament", geoHint: "ტურნამენტი"),
    WordModel(eng: "Pensieve", geo: "პენსივი", engHint: "recollection", geoHint: "მოგონება"),
    WordModel(eng: "Blast-Ended Skrewt", geo: "აფეთქება-კუდიანი სკრუტი", engHint: "hybrid", geoHint: "ჰიბრიდი"),
    WordModel(eng: "Knuts", geo: "კნუტები", engHint: "bronze", geoHint: "ბრინჯაო"),
    WordModel(eng: "Sickles", geo: "სიქლები", engHint: "silver", geoHint: "ვერცხლი"),
    WordModel(eng: "Dueling Club", geo: "დუელის კლუბი", engHint: "practice", geoHint: "პრაქტიკა"),
    WordModel(eng: "Remembrall", geo: "გამახსენებელი", engHint: "forgetfulness", geoHint: "დავიწყება"),
    WordModel(eng: "Boggart", geo: "ბოგარტი", engHint: "fear", geoHint: "შიში"),
    WordModel(eng: "Grindylow", geo: "გრინდილოუ", engHint: "water", geoHint: "წყალი"),
    WordModel(eng: "Inferius", geo: "ინფერიუსი", engHint: "corpse", geoHint: "გვამი"),
    WordModel(eng: "House-elf", geo: "სახლის ელფი", engHint: "servant", geoHint: "მსახური"),
    WordModel(eng: "Gillyweed", geo: "გილვედი", engHint: "gills", geoHint: "ლაფსები"),
    WordModel(eng: "Mandragora", geo: "მანდრაგორა", engHint: "scream", geoHint: "კივილი"),
    WordModel(eng: "Marauder's Map", geo: "მარაუდერის რუკა", engHint: "footprints", geoHint: "ნაფეხურები"),
    WordModel(eng: "Vanishing Cabinet", geo: "გამქრალი კაბინეტი", engHint: "disappearance", geoHint: "გაუჩინარება"),
    WordModel(eng: "Dirigible Plums", geo: "დირიჟაბლი ქლიავი", engHint: "floating", geoHint: "მცურავი"),
    WordModel(eng: "The Daily Prophet", geo: "ყოველდღიური წინასწარმეტყველი", engHint: "newspaper", geoHint: "გაზეთი"),
    WordModel(eng: "Obliviate", geo: "ობლივიეიტი", engHint: "memory-charm", geoHint: "მეხსიერების შელოცვა"),
    WordModel(eng: "Priori Incantatem", geo: "პრიორი ინკანტატემ", engHint: "echo", geoHint: "ექო"),
    WordModel(eng: "Amortentia", geo: "ამორტენცია", engHint: "love-potion", geoHint: "სიყვარულის წამალი"),
    WordModel(eng: "Skele-Gro", geo: "სკელე-გრო", engHint: "bones", geoHint: "ძვლები"),
    WordModel(eng: "Wolfsbane Potion", geo: "მგლისშელოცვის წამალი", engHint: "lycanthropy", geoHint: "ლიკანტროპია"),
    WordModel(eng: "Hagrid's Hut", geo: "ჰაგრიდის ქოხი", engHint: "outskirts", geoHint: "გარეუბანი"),
    WordModel(eng: "Forbidden Forest", geo: "აკრძალული ტყე", engHint: "creatures", geoHint: "არსებები"),
    WordModel(eng: "Platform 9 3/4", geo: "პლატფორმა 9 3/4", engHint: "train", geoHint: "მატარებელი"),
    WordModel(eng: "Triwizard Tournament", geo: "სამი ჯადოქრის ტურნირი", engHint: "competition", geoHint: "კონკურსი"),
    WordModel(eng: "Room of Requirement", geo: "მოთხოვნილებების ოთახი", engHint: "concealed", geoHint: "დაფარული"),
    WordModel(eng: "The Grim", geo: "გრიმი", engHint: "omen", geoHint: "ნიშანი"),
    WordModel(eng: "Deathly Hallows", geo: "სიკვდილის საჩუქრები", engHint: "artifacts", geoHint: "არტეფაქტები"),
    WordModel(eng: "Order of the Phoenix", geo: "ფენიქსის ორდენი", engHint: "resistance", geoHint: "წინააღმდეგობა"),
    WordModel(eng: "Horcrux", geo: "ჰორკრუქსი", engHint: "soul-piece", geoHint: "სულის ნაწილი"),
    WordModel(eng: "Sectumsempra", geo: "სექტუმსემპრა", engHint: "curse", geoHint: "წყევლა"),
    WordModel(eng: "Expecto Patronum", geo: "ექსპექტო პატრონუმ", engHint: "joy", geoHint: "სიხარული"),
    WordModel(eng: "Petrificus Totalus", geo: "პეტრიფიკუს ტოტალუს", engHint: "paralysis", geoHint: "დამბლა"),
    WordModel(eng: "Stupefy", geo: "სტუპეფი", engHint: "stun", geoHint: "გაოგნება"),
    WordModel(eng: "Expelliarmus", geo: "ექსპელიარმუსი", engHint: "disarming", geoHint: "განიარაღება"),
    WordModel(eng: "Lumos", geo: "ლუმოს", engHint: "light", geoHint: "სინათლე"),
    WordModel(eng: "Nox", geo: "ნოქს", engHint: "darkness", geoHint: "სიბნელე"),
    WordModel(eng: "Riddikulus", geo: "რიდიკულუს", engHint: "laughter", geoHint: "სიცილი"),
    WordModel(eng: "Alohomora", geo: "ალოჰომორა", engHint: "unlock", geoHint: "გაღება"),
    WordModel(eng: "Avada Kedavra", geo: "ავადა კედავრა", engHint: "unforgivable", geoHint: "მიუტევებელი"),
    WordModel(eng: "Crucio", geo: "კრუციო", engHint: "pain", geoHint: "ტკივილი"),
    WordModel(eng: "Imperio", geo: "იმპერიო", engHint: "control", geoHint: "კონტროლი"),
    WordModel(eng: "Diffindo", geo: "დიფინდო", engHint: "severing", geoHint: "გაყოფა"),
    WordModel(eng: "Reparo", geo: "რეპარო", engHint: "repair", geoHint: "შეკეთება"),
    WordModel(eng: "Wingardium Leviosa", geo: "ვინგარდიუმ ლევიოსა", engHint: "levitation", geoHint: "ლევიტაცია"),
    WordModel(eng: "Finite Incantatem", geo: "ფინიტე ინკანტატემ", engHint: "ending", geoHint: "დასასრული"),
    WordModel(eng: "Accio", geo: "აციო", engHint: "summon", geoHint: "მოხმობა"),
    WordModel(eng: "Confundo", geo: "კონფუნდო", engHint: "confuse", geoHint: "დაბნევა"),
    WordModel(eng: "Protego", geo: "პროტეგო", engHint: "shield", geoHint: "ფარი"),
    WordModel(eng: "Reducto", geo: "რედუქტო", engHint: "shatter", geoHint: "დამსხვრევა")
]
