//
//  Movies.swift
//  imposter
//
//  Created by Tornike Despotashvili on 8/30/25.
//

import Foundation

let cinematographyData: [WordModel] = [
    WordModel(eng: "Director", geo: "რეჟისორი", engHint: "vision", geoHint: "ხედვა"),
    WordModel(eng: "Actor", geo: "მსახიობი", engHint: "portrayal", geoHint: "განსახიერება"),
    WordModel(eng: "Screenplay", geo: "სცენარი", engHint: "narrative", geoHint: "თხრობა"),
    
    WordModel(eng: "Camera", geo: "კამერა", engHint: "capture", geoHint: "დაფიქსირება"),
    WordModel(eng: "Editing", geo: "მონტაჟი", engHint: "sequence", geoHint: "დაჭრა"),
    WordModel(eng: "Soundtrack", geo: "საუნდტრეკი", engHint: "melody", geoHint: "მელოდია"),
    
    WordModel(eng: "Genre", geo: "ჟანრი", engHint: "category", geoHint: "კატეგორია"),
    WordModel(eng: "Blockbuster", geo: "ბლოკბასტერი", engHint: "hit", geoHint: "ჰიტი"),
    WordModel(eng: "Oscar", geo: "ოსკარი", engHint: "award", geoHint: "ჯილდო"),
    
    WordModel(eng: "Dialogue", geo: "დიალოგი", engHint: "conversation", geoHint: "საუბარი"),
    WordModel(eng: "Sequel", geo: "სიქუელი", engHint: "continuation", geoHint: "გაგრძელება"),
    WordModel(eng: "Trilogy", geo: "ტრილოგია", engHint: "three", geoHint: "სამი"),
    WordModel(eng: "Animated", geo: "ანიმაციური", engHint: "cartoon", geoHint: "მულტფილმი"),
    WordModel(eng: "Documentary", geo: "დოკუმენტური", engHint: "facts", geoHint: "ფაქტები"),
    WordModel(eng: "Thriller", geo: "თრილერი", engHint: "suspense", geoHint: "დაძაბულობა"),
    WordModel(eng: "Comedy", geo: "კომედია", engHint: "laughter", geoHint: "სიცილი"),
    WordModel(eng: "Drama", geo: "დრამა", engHint: "emotions", geoHint: "ემოციები"),
    WordModel(eng: "Sci-Fi", geo: "სამეცნიერო ფანტასტიკა", engHint: "future", geoHint: "მომავალი"),
    WordModel(eng: "Fantasy", geo: "ფანტასტიკა", engHint: "magic", geoHint: "მაგია"),
    WordModel(eng: "Horror", geo: "საშინელებათა", engHint: "fear", geoHint: "შიში"),
    WordModel(eng: "Western", geo: "ვესტერნი", engHint: "cowboys", geoHint: "კოვბოები"),
    WordModel(eng: "Musical", geo: "მიუზიკლი", engHint: "songs", geoHint: "სიმღერები"),
    
    
    
    WordModel(eng: "The Godfather", geo: "ნათლია", engHint: "mafia", geoHint: "მაფია"),
    WordModel(eng: "Shawshank Redemption", geo: "გაქცევა შოუშენკიდან", engHint: "hope", geoHint: "იმედი"),
    WordModel(eng: "Pulp Fiction", geo: "მაკულატურა", engHint: "nonlinear", geoHint: "სამუელი"),
    WordModel(eng: "The Dark Knight", geo: "ბნელი რაინდი", engHint: "hero", geoHint: "გმირი"),
    WordModel(eng: "Forrest Gump", geo: "ფორესტ გამპი", engHint: "life", geoHint: "ცხოვრება"),
    WordModel(eng: "Inception", geo: "დასაწყისი", engHint: "dreams", geoHint: "სიზმრები"),
    WordModel(eng: "Interstellar", geo: "ინტერსტელარი", engHint: "space", geoHint: "კოსმოსი"),
    WordModel(eng: "Matrix", geo: "მატრიცა", engHint: "reality", geoHint: "რეალობა"),
    WordModel(eng: "Gladiator", geo: "გლადიატორი", engHint: "rome", geoHint: "რომი"),
    WordModel(eng: "Titanic", geo: "ტიტანიკი", engHint: "ship", geoHint: "გემი"),
    WordModel(eng: "Avatar", geo: "ავატარი", engHint: "blue", geoHint: "ლურჯი"),
    WordModel(eng: "Joker", geo: "ჯოკერი", engHint: "villain", geoHint: "ბოროტმოქმედი"),
    
    
    WordModel(eng: "La La Land", geo: "ლა ლა ლენდი", engHint: "musical", geoHint: "მუსიკალური"),
    WordModel(eng: "Roma", geo: "რომა", engHint: "black&white", geoHint: "შავ-თეთრი"),
    WordModel(eng: "Her", geo: "მისი", engHint: "AI", geoHint: "ხელოვნური ინტელექტი"),
    WordModel(eng: "Arrival", geo: "ჩამოსვლა", engHint: "aliens", geoHint: "უცხოპლანეტელები"),
    WordModel(eng: "Blade Runner 2049", geo: "ბლეიდ რანერი 2049", engHint: "replicant", geoHint: "რეპლიკანტი"),
    WordModel(eng: "Dune", geo: "დიუნი", engHint: "desert", geoHint: "უდაბნო"),
    WordModel(eng: "1917", geo: "1917", engHint: "war", geoHint: "ომი"),
    WordModel(eng: "Green Book", geo: "მწვანე წიგნი", engHint: "roadtrip", geoHint: "წიგნი"),
    WordModel(eng: "Birdman", geo: "ადამიანი ჩიტი", engHint: "theatre", geoHint: "თეატრი"),
    WordModel(eng: "The Revenant", geo: "გადარჩენილი", engHint: "survival", geoHint: "გადარჩენა"),
    WordModel(eng: "Mad Max: Fury Road", geo: "შეშლილი მაქსი: მრისხანების გზა", engHint: "post-apocalyptic", geoHint: "პოსტ-აპოკალიფსური"),
    WordModel(eng: "Spotlight", geo: "ყურადღების ცენტრში", engHint: "journalism", geoHint: "ჟურნალისტიკა"),
    WordModel(eng: "A Star Is Born", geo: "ვარსკვლავი დაიბადა", engHint: "music", geoHint: "მუსიკა"),
    WordModel(eng: "Marriage Story", geo: "ქორწინების ისტორია", engHint: "divorce", geoHint: "განქორწინება"),
    WordModel(eng: "Nomadland", geo: "ნომადლენდი", engHint: "van", geoHint: "ფურგონი"),
    WordModel(eng: "The Power of the Dog", geo: "ძაღლის ძალა", engHint: "western", geoHint: "ვესტერნი"),
    WordModel(eng: "CODA", geo: "CODA", engHint: "family", geoHint: "ოჯახი"),
    WordModel(eng: "Everything Everywhere All at Once", geo: "ყველაფერი ყველგან ერთდროულად", engHint: "multiverse", geoHint: "მულტივერსი"),
    WordModel(eng: "Oppenheimer", geo: "ოპენჰაიმერი", engHint: "bomb", geoHint: "ბომბი"),
    WordModel(eng: "Poor Things", geo: "საბრალო არსებები", engHint: "frankenstein", geoHint: "ფრანკენშტეინი"),
    WordModel(eng: "Past Lives", geo: "წარსული ცხოვრება", engHint: "destiny", geoHint: "ბედისწერა"),
    WordModel(eng: "Anatomy of a Fall", geo: "დაცემის ანატომია", engHint: "court", geoHint: "სასამართლო"),
    WordModel(eng: "The Holdovers", geo: "დარჩენილები", engHint: "teacher", geoHint: "მასწავლებელი"),
    WordModel(eng: "Killers of the Flower Moon", geo: "ყვავილოვანი მთვარის მკვლელები", engHint: "oil", geoHint: "ზეთი"),
    WordModel(eng: "Maestro", geo: "მაესტრო", engHint: "conductor", geoHint: "დირიჟორი"),
    WordModel(eng: "Barbie", geo: "ბარბი", engHint: "doll", geoHint: "თოჯინა"),
    WordModel(eng: "Spider-Man: Across the Spider-Verse", geo: "ადამიანი-ობობა: განზომილებებს მიღმა", engHint: "superhero", geoHint: "სუპერგმირი"),
    WordModel(eng: "Guardians of the Galaxy Vol. 3", geo: "გალაქტიკის მცველები ტომი 3", engHint: "space", geoHint: "კოსმოსი"),
    WordModel(eng: "Mission: Impossible - Dead Reckoning Part One", geo: "მისია შეუძლებელია - საბედისწერო ანგარიში, ნაწილი პირველი", engHint: "spy", geoHint: "ჯაშუში"),
    WordModel(eng: "Indiana Jones and the Dial of Destiny", geo: "ინდიანა ჯონსი და ბედისწერის ციფერბლატი", engHint: "archeology", geoHint: "არქეოლოგია"),
    WordModel(eng: "Wonka", geo: "ვონკა", engHint: "chocolate", geoHint: "შოკოლადი"),
    WordModel(eng: "Migration", geo: "მიგრაცია", engHint: "ducks", geoHint: "იხვები"),
    WordModel(eng: "Elemental", geo: "სტიქიური", engHint: "elements", geoHint: "ელემენტები"),
    WordModel(eng: "Wish", geo: "სურვილი", engHint: "stars", geoHint: "ვარსკვლავები"),
    WordModel(eng: "The Little Mermaid", geo: "პატარა ქალთევზა", engHint: "underwater", geoHint: "წყალქვეშ"),
    WordModel(eng: "Fast X", geo: "ფორსაჟი X", engHint: "cars", geoHint: "მანქანები"),
    WordModel(eng: "John Wick: Chapter 4", geo: "ჯონ უიკი: თავი 4", engHint: "assassin", geoHint: "მკვლელი"),
    WordModel(eng: "Creed III", geo: "კრიდი III", engHint: "boxing", geoHint: "კრივი"),
    WordModel(eng: "Ant-Man and the Wasp: Quantumania", geo: "ადამიანი-ჭიანჭველა და კრაზანა: კვანტომანია", engHint: "quantum", geoHint: "კვანტური"),
    WordModel(eng: "The Super Mario Bros. Movie", geo: "სუპერ მარიო ძმების ფილმი", engHint: "game", geoHint: "თამაში"),
    WordModel(eng: "Puss in Boots: The Last Wish", geo: "ჩექმებიანი კატა: უკანასკნელი სურვილი", engHint: "feline", geoHint: "ფისო"),
    WordModel(eng: "Turning Red", geo: "წითლად გადაქცევა", engHint: "panda", geoHint: "პანდა"),
    WordModel(eng: "Encanto", geo: "ენკანტო", engHint: "magic", geoHint: "მაგია"),
    WordModel(eng: "Luca", geo: "ლუკა", engHint: "sea", geoHint: "ზღვა"),
    WordModel(eng: "Soul", geo: "სული", engHint: "music", geoHint: "მუსიკა"),
    WordModel(eng: "Raya and the Last Dragon", geo: "რაია და უკანასკნელი დრაკონი", engHint: "dragon", geoHint: "დრაკონი"),
    WordModel(eng: "Cruella", geo: "კრუელა", engHint: "fashion", geoHint: "მოდა"),
    WordModel(eng: "Black Widow", geo: "შავი ქვრივი", engHint: "spy", geoHint: "ჯაშუში"),
    WordModel(eng: "Shang-Chi and the Legend of the Ten Rings", geo: "შანგ-ჩი და ათი ბეჭდის ლეგენდა", engHint: "martial arts", geoHint: "ორთაბრძოლა"),
    WordModel(eng: "Eternals", geo: "მარადიულები", engHint: "celestials", geoHint: "ცელესტიალები"),
    WordModel(eng: "No Time to Die", geo: "სიკვდილის დრო არ არის", engHint: "bond", geoHint: "ბონდი"),
    WordModel(eng: "Top Gun: Maverick", geo: "საუკეთესო მსროლელი: მავერიკი", engHint: "pilot", geoHint: "პილოტი"),
    WordModel(eng: "Doctor Strange in the Multiverse of Madness", geo: "დოქტორი სტრეინჯი სიგიჟის მულტივერსში", engHint: "magic", geoHint: "მაგია"),
    WordModel(eng: "Thor: Love and Thunder", geo: "თორი: სიყვარული და ჭექა-ქუხილი", engHint: "god", geoHint: "ღმერთი"),
    WordModel(eng: "Black Panther: Wakanda Forever", geo: "შავი პანტერა: ვაკანდა სამუდამოდ", engHint: "africa", geoHint: "აფრიკა"),
    WordModel(eng: "Avatar: The Way of Water", geo: "ავატარი: წყლის გზა", engHint: "oceans", geoHint: "ოკეანეები"),
    WordModel(eng: "Glass Onion: A Knives Out Mystery", geo: "შუშის ხახვი: დანებით ამოღებული საიდუმლო", engHint: "detective", geoHint: "დეტექტივი"),
    WordModel(eng: "The Banshees of Inisherin", geo: "ინიშერინის ბანში", engHint: "island", geoHint: "კუნძული"),
    WordModel(eng: "All Quiet on the Western Front", geo: "ყველა სიწყნარე დასავლეთის ფრონტზე", engHint: "war", geoHint: "ომი")
]
